### ISSUE TITLE
New-DuoUser Error

### ISSUE THREAD

**Issue by dmrbond** [johnduprey/DuoSecurity#16]
When attempting to get a create new user with New-DuoUser in the admin API, it seems to return an error referencing aliases.  I was able to use Get-DuoUsers just fine.  Specifying my own aliases for the user didn't seem to matter either.

`code           : 40002
message        : Invalid request parameters
message_detail : aliases
stat           : FAIL`

Here is what I was running:
````
Set-DuoApiAuth @Auth

$username = "lukeskywalker"
$fullname = "Luke Skywalker"
$emaill = "lukeskywalker@lakeview2167.com"
$aliases = @{alias1='goldleader'; alias2='redleader'}

New-DuoUser -Username $username -FullName $fullname -Email $email
````

**Comment by johnduprey** [comment]
Hey @dmrbond, thanks for reporting this. I think I've tracked it down. Will be pushing an update to the module soon.
