### ISSUE TITLE
Something is wrong with the Headers

### ISSUE THREAD

**Issue by HelgeDechow** [JohnDuprey/DuoSecurity#32]
Since a few days I get the

code    message                                stat
40104  Missing request timestamp  FAIL

on pretty much every function I run against the Admin API. After some digging I found out that you have to set the regional format to English (United States) for your invoke-request function to work. 
Maybe you consider to update your XDuoDate Get function to also convert days and so on to English if possible.

My regional format was set to German where Wednesday is Mittwoch and therefore $XDuoDate contained Mi, 14...

**Comment by JohnDuprey** [comment]
Thanks for the report. I've pushed a new release that sets the localization to en-US for the canonicalized headers. Please try out version 1.4.1 and let me know if that fixes it for you.
