### ISSUE TITLE
v2 API support

### ISSUE THREAD

**Issue by Venom-Host** [JohnDuprey/DuoSecurity#35]
Do you have plans to finish implementing v2 API support? For example, we were able to get Get-DuoIntegrations to work by simply changing the Path and SignatureVersion

![duoissue](https://github.com/JohnDuprey/DuoSecurity/assets/50363681/e4983c26-5687-45aa-87df-2f341fb79fea)

Is this something you could implement so that we don't have to modify it on our end?

Great module by the way!

**Comment by JohnDuprey** [comment]
Nice suggestion! Feel free to submit a PR and I'll check it out. You should be able to tweak that right from GitHub web.

**Comment by JohnDuprey** [comment]
All set, new release is publishing to the gallery now

**Comment by Venom-Host** [comment]
whooo hoooo, thanks so much for working with us on this!

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
