### ISSUE TITLE
Authentication Fails

### ISSUE THREAD

**Issue by mpunderw** [JohnDuprey/DuoSecurity#38]
I'm not able to authenticate to the Duo service. I run Set-DuoApiAuth, but no matter what I try I'm not able to get information. 

What application in Duo is required? I have the Auth API and Duo API applications both setup and neither seem to work as expected. When you run the Set-DuoApiAuth the "Type" what's the difference between Accounts, Auth, and Admin. Does it matter which one you use since it appears you can run any command with any type. Does the type correspond to different applications in Duo?

Depending on the Duo app and type I get a variety of error messages either Access forbidden or Invalid identity in request credentials.

**Comment by JohnDuprey** [comment]
It depends on what API you're targeting. If you're a Duo Partner and need to access child accounts, you'll need the Accounts API. If you just want to modify settings in your own Duo tenant you need the Admin API. If you want to send push notifications, use the Auth API.

If you look at the Public folder in the DuoSecurity module in GitHub, you'll see that each API is segmented into their respective folders. The only exception to this is the Accounts API as it's just a wrapper around the Admin API.

**Comment by mpunderw** [comment]
Thanks for the info, I feel like there's a bunch of prereq information that I'm missing. 

I'm trying to pull a basic list of users from our own Duo tenant, I run the Set-DuoApiAuth using Type Admin and when I run Get-DuoUsers, I get 40102 Invalid identity in request credentials FAIL. I've used the integration key and secret from the Auth API and from the Duo API applications and both get the same error.

**Comment by JohnDuprey** [comment]
The Auth API is specifically for sending push notifications, it does not work for anything else. You'll need to create an Admin API application and enable the correct settings.

This should point you in the right direction:
https://duo.com/docs/adminapi#first-steps

**Comment by mpunderw** [comment]
I have figured out the issue, we weren't using the Admin API. Once enabled and given the correct permissions the PowerShell module started returning the correct information. This issue can be closed.
