### ISSUE TITLE
update-duouser -aliases does not work

### ISSUE THREAD

**Issue by tomgregoryucr** [JohnDuprey/DuoSecurity#40]
-Aliases parameter of update-duouser does not work.  

Below is a workaround fix I implemented that you can use/modify/incorporate as you see fit:
The <# #> section is your original code.

       if ($Aliases) {
            $x = 1
            
<#            $AliasList = foreach ($Alias in $Aliases) {
                if ($x -gt 8) { break }
                @{"alias$x" = $Alias }
                $x++
            }
#>

###  Fix
        $AliasList = ""
        foreach ($Alias in $Aliases) {
          if ($x -gt 8) {break}
          if ($x -eq 1) {
              $AliasList = "alias$x" + "=" + $Alias
          }
          else {
            $AliasList += "&alias$x" + "=" + $Alias
          }

### end Fix
          $x++
        }
            $Params.aliases = $AliasList
            $AliasList
        }

**Comment by tomgregoryucr** [comment]
Sorry, actual fix needs the $x++ and }

$AliasList = ""
    foreach ($Alias in $Aliases) {
      if ($x -gt 8) {break}
      if ($x -eq 1) {
          $AliasList = "alias$x" + "=" + $Alias
      }
      else {
        $AliasList += "&alias$x" + "=" + $Alias
      }
      $x++
    }

**Comment by JohnDuprey** [comment]
Fixed it in a cleaner way, += is not optimal

**Comment by tomgregoryucr** [comment]
Perfect.  I just needed -Aliases to work.  I’ll test with the updated code.

Thanks!

Tom Gregory
